# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gqls < Formula
  desc "GraphQL vulnerability scanner — find security issues in your GraphQL APIs"
  homepage "https://github.com/omkoli/GQLS-CLI"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/omkoli/GQLS-CLI/releases/download/v0.1.0/GQLS-CLI_darwin_amd64.tar.gz"
      sha256 "cd47fff21e7c139ae0d4115fd6f25cb5ca8209708e82576c9de786ea8f375305"

      define_method(:install) do
        bin.install "gqls"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/omkoli/GQLS-CLI/releases/download/v0.1.0/GQLS-CLI_darwin_arm64.tar.gz"
      sha256 "dbbc3b63419aefc2eadf5c1d58378f9e19ad68cca74e9a2e8558e2284ece8c57"

      define_method(:install) do
        bin.install "gqls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/omkoli/GQLS-CLI/releases/download/v0.1.0/GQLS-CLI_linux_amd64.tar.gz"
      sha256 "7225a66efd6923ab66444ab29c4de93fda99e6b435f75ae666d4464bb91a1275"
      define_method(:install) do
        bin.install "gqls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/omkoli/GQLS-CLI/releases/download/v0.1.0/GQLS-CLI_linux_arm64.tar.gz"
      sha256 "8b3ccea6c9bdef7106c5dded471c8f6815adf14d9dad58c0aa6950fad22f9651"
      define_method(:install) do
        bin.install "gqls"
      end
    end
  end

  test do
    system "#{bin}/gqls", "--version"
  end
end
